### ISSUE TITLE
123 as summon request

### ISSUE THREAD

**Issue by Grindlewalde** [Sentilix/capslock#1]
Hey - Love the app, recommending all locks in our guild get it. I looked in the TUA and it seems to recognize 123 as a request for summon, but in-game the only thing its recognizing is "!summon. It's a bit tough for people to remember to put a space or a " before the !summon, so we'd prefer 123. Any easy fix so that 123 works the same was "!summon works?

**Comment by Sentilix** [comment]
Hi,
The plan is to make the trigger word configurable. The reason why I did not chose "123" as trigger word initially is because people also often tend to ask "HEALERS 123" - this would cause healers to be summoned when they replied :-)

**Comment by Sentilix** [comment]
I am closing this. The "123" will - as mentioned above - be configuable in a later release.
